apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-notifier
spec:
  selector:
    matchLabels:
      app: k8s-notifier
  template:
    metadata:
      labels:
        app: k8s-notifier
    spec:
      containers:
        - name: k8s-notifier
          image: ghcr.io/janpf/k8s-notifications:latest
          imagePullPolicy: "Always"
          args:
            - --events_to_notify
            - ERROR
            - DONE
            - ADDED
            - DELETED
            - MODIFIED
            - --notification_channels
            - rocketchat
            - elasticsearch
          env:
            - name: HOME
              value: "/home/k8snotif"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: ".1"
              memory: ".5Gi"
          volumeMounts:
            - mountPath: /home/k8snotif/.kube
              name: home
              subPath: .kube
              readOnly: true
            - mountPath: /home/k8snotif/.nofconfig
              name: home
              subPath: .nofconfig
              readOnly: true
      volumes:
        - name: home
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: pfister # TODO how to make user and path dynamic?
            path: "/home/ls6/pfister"
            secretRef:
              name: ceph-secret